### PR TITLE
Fail gracefully

### PR DESCRIPTION
**Pull request by AydinHassan**
@mikeymike What do you think to this? Any suggestions?

### CODE REVIEW

**Comment by AydinHassan** [comment]
@mikeymike We should put a link to the install docs when they are up in there also

**Comment by mikeymike** [comment]
@AydinHassan 100% agree with this, I can't see anyway around it. Most of the big packages do this too.

**Comment by AydinHassan** [comment]
@mikeymike I'll test it and merge in tomorrow and update learn-you-php

**Comment by mikeymike** [comment]
@AydinHassan do you think we could do an OS detect and provide a link on how to update the PATH under option 1 ?

**Comment by AydinHassan** [comment]
yeah defo, I'll look in to that.

**Comment by mikeymike** [comment]
or maybe just a link to [Let me Google that for you](http://lmgtfy.com/?q=edit+system+path+on+windows) :trollface:

**Pull request merged**
